# base image
FROM node:12.2.0 as build

# install chrome for protractor tests
#RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
#RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
#RUN apt-get update && apt-get install -yq google-chrome-stable

# set working directory
WORKDIR /web-app-wall

# add `/app/node_modules/.bin` to $PATH
ENV PATH /web-app-wall/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /web-app-wall/package.json
RUN npm install
RUN npm install -g @angular/cli@10.0.5

# add app
COPY . /web-app-wall

# run tests
#RUN ng test --watch=false
#RUN ng e2e --port 4202

# generate build
RUN ng build --output-path=dist

############
### prod ###
############

# base image
FROM nginx:1.16.0-alpine

EXPOSE 4200
# copy artifact build from the 'build environment'
COPY --from=build /web-app-wall/dist /usr/share/nginx/html

# run nginx
# CMD ["nginx", "-g", "daemon off;"]
CMD ["/bin/sh", "-c", "sed -i 's/listen  .*/listen 4200;/g' /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]